### ISSUE TITLE
Upgrading to grpc-labview 1.0.0.2 or later breaks measurement service

### ISSUE THREAD

**Issue by cumitche** [ni/measurementlink-labview#235]
# Bug Report

Upgrading grpc-labview to a newer version that what is provided in the release assets causes InstrumentStudio to be unable to connect to running LabVIEW measurement services.

## Repro or Code Sample

Upgrade grpc-labview from 1.0.0.1 to 1.0.0.2 or later.  Run a LabVIEW measurement service.  Add the service to a large panel in InstrumentStudio.

## Expected Behavior

Measurement service should load UI and run in InstrumentStudio.

## Current Behavior

![image](https://github.com/ni/measurementlink-labview/assets/77293599/9c9ebf6a-f0b1-4bae-958e-5ccaac8546ee)
Measurement service fails to load UI and displays an error stating that it cannot connect to the measurement.

## Context

Attempted to use the latest release of grpc-labview (1.0.0.5) to regenerate a client and discovered the breakage.  Traced it back to 1.0.0.2.  This issue is not blocking me, I can continue to use 1.0.0.1 for now.

## Your Environment

* OS & Device: Windows 10 on PC
* `ni-measurement-service` version 1.0.1.1
* MeasurementLink version 23.3.0f793
* Python version N/A

[AB#2455408](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2455408)

**Comment by pbirkhol-ni** [comment]
I looked into this today. The issue is caused by `grpc-labview` adding enum support. Before `grpc-labview` had enums, it would use integers as enum values. The generated messages would use integers in place of enums and that is what the generated v1 and v2 measurements use in `measurmentlink-labview` (the v1 and v2 measurements don't use enums directly, but they do use google types that are enums). When upgrading to `grpc-labview v1.0.0.2` or later, the expectation is that any enum messages will use LabVIEW enums and not integers. So if you don't regenerate the gRPC messages, setting response data will throw an unhandled exception. See [here](https://github.com/ni/grpc-labview/blob/cab29387ed6d9e0889626b3233e7ce74afac3c2b/src/grpc_interop.cc#L401C42-L401C57). This happens in `measurementlink-labview` during calls to `GetMetadata.`

Unfortunately, due to another [bug](https://github.com/ni/grpc-labview/pull/267), we can't regenerate the measurements. This bug has been fixed, but is not in an official release. Once it is in an official release, we can regenerate the v1 and v2 measurements using `grpc-labview 1.0.0.6`, which should fix this issue. Note, though, that the regenerated measurements will _not_ be compatible with older versions for grpc-labview. They will require `grpc-labview 1.0.0.6` or later.
