### ISSUE TITLE
When invalid LabVIEW VIs are used as UI in the G plugin then no error is thrown and an empty screen is loaded 

### ISSUE THREAD

**Issue by subash-suresh** [ni/measurementlink-labview#38]
When a UI file is given as a Labview VI and if it is either invalid or not found,no error is thrown and a blank screen is loaded 
![image](https://user-images.githubusercontent.com/98541596/160446668-b5a4f761-f008-48f6-81c4-d431eb93aee6.png)

[AB#2270676](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2270676)

**Comment by jasonmreding** [comment]
This issue is pretty old so things look quite a bit different now. If the VI can't be found, here is what I currently see:

![image](https://user-images.githubusercontent.com/103200169/213800394-c1eff2c3-847f-47de-ab4e-515343f1f2f1.png)

You get a document alert that you can dismiss, and once dismissed, it doesn't come back. The main document area doesn't show anything, and you can still run the measurement even though there is no way to observe the results or change inputs from the defaults defined by the measurement. Maybe we should do better with disabling the RUN button in these cases?

Here is what it looks like if the VI isn't runnable:

![image](https://user-images.githubusercontent.com/103200169/213800794-7c283c10-61b6-4bc7-b9a1-51f04ba26131.png)

In this case, the document just displays some pretty crude error information returned from our plugin based on the error string in the error cluster. I think there are some error chaining issues in the plugin implementation that are probably preventing better error strings, but I'm not certain. We also don't set any error states that are displayed with a document alert. Again, you can still run the measurement even though there is no way to visualize or interact with it and see results.

**Comment by dixonjoel** [comment]
@subash-suresh Let's close this issue since it's quite old. If you want to file a newer issue with updated screenshots that you think is worth fixing feel free to do that.
